set TgtName=fltk
set TgtDir=
set GitUrl=https://github.com/fltk/fltk.git
set SrcIncSubDir=FL
set InstallIncSubDir=FL
set InstallLibSubDir=
set hdr1=*
set hdr2=
set hdr3=
set hdr4=
set hdr5=
set hdr6=
set hdr7=
set hdr8=
set hdr9=
set Arg=
rem set NoInstall=1
set CcTgtBldDir=build
set CcTgtLibDir=lib
rem set ZlibDir=%CcLibsRoot%\zlib
rem set PngDir=%CcLibsRoot%\libpng
rem set JpegDir=%CcLibsRoot%\jpeg
set NeedTinyReplStr=1
